import { AuditLogEntry, DocumentItem } from "./Documents.types";

export const DOCUMENTS_MOCK: DocumentItem[] = [
  {
    id: "doc-1",
    name: "Referral - John Smith",
    originalName: "referral-john-smith.pdf",
    fileType: "pdf",
    fileSize: 2540012,
    fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    thumbnailUrl: null,
    category: "referral",
    tags: ["new-client", "priority"],
    isConfidential: false,
    client: { id: "c-1", fullName: "John Smith", avatar: null },
    therapist: { id: "t-1", fullName: "Dr. Emily Carter", avatar: null },
    uploadedByName: "Sarah Admin",
    uploadedAt: "2026-03-16T09:10:00.000Z",
    updatedAt: "2026-03-16T09:10:00.000Z",
  },
  {
    id: "doc-2",
    name: "Assessment Scan",
    originalName: "assessment-jane.jpg",
    fileType: "jpg",
    fileSize: 1103321,
    fileUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1200&auto=format&fit=crop",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=600&auto=format&fit=crop",
    category: "assessment",
    tags: ["scan"],
    isConfidential: true,
    client: { id: "c-2", fullName: "Jane Miller", avatar: null },
    therapist: { id: "t-2", fullName: "Dr. Noah Lee", avatar: null },
    uploadedByName: "Mia Coordinator",
    uploadedAt: "2026-03-15T12:35:00.000Z",
    updatedAt: "2026-03-18T10:20:00.000Z",
  },
  {
    id: "doc-3",
    name: "Consent Form - Olivia",
    originalName: "consent-olivia.docx",
    fileType: "docx",
    fileSize: 402111,
    fileUrl: "#",
    thumbnailUrl: null,
    category: "consent_form",
    tags: [],
    isConfidential: false,
    client: { id: "c-3", fullName: "Olivia Brown", avatar: null },
    therapist: { id: "t-1", fullName: "Dr. Emily Carter", avatar: null },
    uploadedByName: "Sarah Admin",
    uploadedAt: "2026-03-12T08:00:00.000Z",
    updatedAt: "2026-03-14T09:00:00.000Z",
  },
  {
    id: "doc-4",
    name: "Progress Report - Weekly",
    originalName: "progress-report-03-10.pdf",
    fileType: "pdf",
    fileSize: 830112,
    fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    thumbnailUrl: null,
    category: "progress_report",
    tags: ["weekly"],
    isConfidential: false,
    client: { id: "c-4", fullName: "James Wilson", avatar: null },
    therapist: { id: "t-3", fullName: "Dr. Sophie Davis", avatar: null },
    uploadedByName: "System User",
    uploadedAt: "2026-03-10T15:30:00.000Z",
    updatedAt: "2026-03-10T15:30:00.000Z",
  },
];

export const AUDIT_LOGS_MOCK: AuditLogEntry[] = [
  {
    id: "audit-1",
    documentId: "doc-1",
    action: "uploaded",
    performedByName: "Sarah Admin",
    performedAt: "2026-03-16T09:10:00.000Z",
    meta: null,
  },
  {
    id: "audit-2",
    documentId: "doc-1",
    action: "downloaded",
    performedByName: "Dr. Emily Carter",
    performedAt: "2026-03-17T10:18:00.000Z",
    meta: null,
  },
  {
    id: "audit-3",
    documentId: "doc-2",
    action: "confidential_toggled",
    performedByName: "Mia Coordinator",
    performedAt: "2026-03-18T10:20:00.000Z",
    meta: { newStatus: "true" },
  },
];
