import { History } from "lucide-react";
import { REPORT_TYPE_LABEL } from "@/data/reportsData/reportsDashboardData";
import { ExportFormat, ReportHistoryEntry, ReportType } from "@/types/reportsDashboardTypes";
import { fmtDate, fmtDateTime } from "@/utils/reportsDashboardUtils";
import styles from "./ReportsDashboardPage.module.css";

interface ReportsHistoryTabProps {
  historyTypeFilter: "all" | ReportType;
  historyFormatFilter: "all" | ExportFormat;
  historyRows: ReportHistoryEntry[];
  historyPage: number;
  historyTotalPages: number;
  onTypeChange: (value: "all" | ReportType) => void;
  onFormatChange: (value: "all" | ExportFormat) => void;
  onClear: () => void;
  onPrev: () => void;
  onNext: () => void;
  onRerun: () => void;
}

export function ReportsHistoryTab(props: ReportsHistoryTabProps) {
  const {
    historyTypeFilter,
    historyFormatFilter,
    historyRows,
    historyPage,
    historyTotalPages,
    onTypeChange,
    onFormatChange,
    onClear,
    onPrev,
    onNext,
    onRerun,
  } = props;

  return (
    <section className={styles.section}>
      <div className={styles.row}>
        <select className={styles.select} value={historyTypeFilter} onChange={(e) => onTypeChange(e.target.value as "all" | ReportType)}>
          <option value="all">All Types</option>
          {(Object.keys(REPORT_TYPE_LABEL) as ReportType[]).map((type) => (
            <option key={type} value={type}>
              {REPORT_TYPE_LABEL[type]}
            </option>
          ))}
        </select>
        <select className={styles.select} value={historyFormatFilter} onChange={(e) => onFormatChange(e.target.value as "all" | ExportFormat)}>
          <option value="all">All Formats</option>
          <option value="pdf">PDF</option>
          <option value="excel">Excel</option>
          <option value="csv">CSV</option>
        </select>
        <button type="button" className={styles.secondaryButton} onClick={onClear}>
          Clear
        </button>
      </div>
      {historyRows.length === 0 ? (
        <div className={styles.emptyState}>
          <History size={18} />
          <p>No report history yet.</p>
        </div>
      ) : (
        <>
          <div className={styles.tableWrap}>
            <table className={styles.table}>
              <thead>
                <tr>
                  <th>Generated At</th>
                  <th>Type</th>
                  <th>Period</th>
                  <th>Generated By</th>
                  <th>Format</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {historyRows.map((item) => (
                  <tr key={item.id}>
                    <td>{fmtDateTime(item.generatedAt)}</td>
                    <td>{REPORT_TYPE_LABEL[item.type]}</td>
                    <td>
                      {fmtDate(item.filters.from)} - {fmtDate(item.filters.to)}
                    </td>
                    <td>{item.generatedBy}</td>
                    <td>{item.exportFormat ? item.exportFormat.toUpperCase() : "-"}</td>
                    <td>
                      <div className={styles.row}>
                        <button type="button" className={styles.ghostButton}>
                          Download
                        </button>
                        <button type="button" className={styles.ghostButton} onClick={onRerun}>
                          Re-run
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className={styles.pagination}>
            <button type="button" className={styles.secondaryButton} disabled={historyPage <= 1} onClick={onPrev}>
              Previous
            </button>
            <span>
              {historyPage} / {historyTotalPages}
            </span>
            <button type="button" className={styles.secondaryButton} disabled={historyPage >= historyTotalPages} onClick={onNext}>
              Next
            </button>
          </div>
        </>
      )}
    </section>
  );
}
